name: batteries test build

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    name: batteries test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: install elan and build doc-gen4
        uses: leanprover/lean-action@v1

      - name: Checkout batteries
        run: |
          cd ../
          git clone https://github.com/leanprover-community/batteries

      - name: generate docs
        run: |
          cd ../
          ./doc-gen4/test_docs.sh "batteries" "doc-gen4"
